version: "3.3"

services:
  db:
    image: mysql:5.7
    container_name: db
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user-services
      MYSQL_ROOT_HOST: "%"
    command: ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]

  app:
    build: .
    image: user-services
    container_name: user-services
    restart: always
    ports:
      - 8080:8080
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_NAME=user-services
    depends_on:
      - db
volumes:
  db_data: {}
